### ISSUE TITLE
Thoughtcomplete API

### ISSUE THREAD

**Issue by MichaelDanilov** [now-examples/thoughtcomplete#3]
Hello!

Are you sure that [Thoughtcomplete API](https://github.com/now-examples/thoughtcomplete-api) exists and public for all?

Because link to it in Readme-file doesn't work.

**Comment by hemanth** [comment]
Came looking for the same.

**Comment by Kikobeats** [comment]
it exists but is not public: https://thoughtcomplete-api.now.sh/_src

**Comment by nkzawa** [comment]
It's public now, sorry for the delay!
